### ISSUE TITLE
The hash for every message/file is the same

### ISSUE THREAD

**Issue by ankush-soni** [afknst/python-sha3#1]
The hash computation after executing the shake128.py file is same for every file. Seems like it is reading the same content over and over despite inputting some other file.
Can you help?

**Comment by afknst** [comment]
What is the command you're using? Everything works fine when I test ...
![Untitled](https://user-images.githubusercontent.com/56207996/129555865-fbe4aa97-e548-41c8-bbfb-9094c44b72fa.png)

**Comment by afknst** [comment]
Maybe you forgot the `<` sign?
